[pytest]
markers =
    fast: Pruebas unitarias rápidas con Mocks, sin I/O, APIs ni GPU.
    integration: Pruebas complejas que pueden requerir RAM/VRAM y descargar pesos de internet.
testpaths =
    tests
pythonpath = .
